package org.saas.report.entity;

public class S02DecAmtKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_amt.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String yr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_amt.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String dtTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_amt.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String decDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_amt.yr
     *
     * @return the value of s02_dec_amt.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getYr() {
        return yr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_amt.yr
     *
     * @param yr the value for s02_dec_amt.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setYr(String yr) {
        this.yr = yr == null ? null : yr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_amt.dt_typ
     *
     * @return the value of s02_dec_amt.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getDtTyp() {
        return dtTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_amt.dt_typ
     *
     * @param dtTyp the value for s02_dec_amt.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDtTyp(String dtTyp) {
        this.dtTyp = dtTyp == null ? null : dtTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_amt.dec_dt
     *
     * @return the value of s02_dec_amt.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getDecDt() {
        return decDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_amt.dec_dt
     *
     * @param decDt the value for s02_dec_amt.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecDt(String decDt) {
        this.decDt = decDt == null ? null : decDt.trim();
    }
}