package org.saas.report.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class S02DecStatYrExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public S02DecStatYrExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYrIsNull() {
            addCriterion("yr is null");
            return (Criteria) this;
        }

        public Criteria andYrIsNotNull() {
            addCriterion("yr is not null");
            return (Criteria) this;
        }

        public Criteria andYrEqualTo(String value) {
            addCriterion("yr =", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotEqualTo(String value) {
            addCriterion("yr <>", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThan(String value) {
            addCriterion("yr >", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThanOrEqualTo(String value) {
            addCriterion("yr >=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThan(String value) {
            addCriterion("yr <", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThanOrEqualTo(String value) {
            addCriterion("yr <=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLike(String value) {
            addCriterion("yr like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotLike(String value) {
            addCriterion("yr not like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrIn(List<String> values) {
            addCriterion("yr in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotIn(List<String> values) {
            addCriterion("yr not in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrBetween(String value1, String value2) {
            addCriterion("yr between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotBetween(String value1, String value2) {
            addCriterion("yr not between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andAmtIsNull() {
            addCriterion("amt is null");
            return (Criteria) this;
        }

        public Criteria andAmtIsNotNull() {
            addCriterion("amt is not null");
            return (Criteria) this;
        }

        public Criteria andAmtEqualTo(BigDecimal value) {
            addCriterion("amt =", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotEqualTo(BigDecimal value) {
            addCriterion("amt <>", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThan(BigDecimal value) {
            addCriterion("amt >", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amt >=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThan(BigDecimal value) {
            addCriterion("amt <", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amt <=", value, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtIn(List<BigDecimal> values) {
            addCriterion("amt in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotIn(List<BigDecimal> values) {
            addCriterion("amt not in", values, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amt between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amt not between", value1, value2, "amt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtIsNull() {
            addCriterion("amt_sm_rt is null");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtIsNotNull() {
            addCriterion("amt_sm_rt is not null");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtEqualTo(BigDecimal value) {
            addCriterion("amt_sm_rt =", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtNotEqualTo(BigDecimal value) {
            addCriterion("amt_sm_rt <>", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtGreaterThan(BigDecimal value) {
            addCriterion("amt_sm_rt >", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("amt_sm_rt >=", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtLessThan(BigDecimal value) {
            addCriterion("amt_sm_rt <", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("amt_sm_rt <=", value, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtIn(List<BigDecimal> values) {
            addCriterion("amt_sm_rt in", values, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtNotIn(List<BigDecimal> values) {
            addCriterion("amt_sm_rt not in", values, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amt_sm_rt between", value1, value2, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andAmtSmRtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("amt_sm_rt not between", value1, value2, "amtSmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtyIsNull() {
            addCriterion("dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andDecQtyIsNotNull() {
            addCriterion("dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andDecQtyEqualTo(Integer value) {
            addCriterion("dec_qty =", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyNotEqualTo(Integer value) {
            addCriterion("dec_qty <>", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyGreaterThan(Integer value) {
            addCriterion("dec_qty >", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("dec_qty >=", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyLessThan(Integer value) {
            addCriterion("dec_qty <", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("dec_qty <=", value, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyIn(List<Integer> values) {
            addCriterion("dec_qty in", values, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyNotIn(List<Integer> values) {
            addCriterion("dec_qty not in", values, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("dec_qty between", value1, value2, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("dec_qty not between", value1, value2, "decQty");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtIsNull() {
            addCriterion("dec_qty_sm_rt is null");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtIsNotNull() {
            addCriterion("dec_qty_sm_rt is not null");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtEqualTo(BigDecimal value) {
            addCriterion("dec_qty_sm_rt =", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtNotEqualTo(BigDecimal value) {
            addCriterion("dec_qty_sm_rt <>", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtGreaterThan(BigDecimal value) {
            addCriterion("dec_qty_sm_rt >", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_sm_rt >=", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtLessThan(BigDecimal value) {
            addCriterion("dec_qty_sm_rt <", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_sm_rt <=", value, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtIn(List<BigDecimal> values) {
            addCriterion("dec_qty_sm_rt in", values, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtNotIn(List<BigDecimal> values) {
            addCriterion("dec_qty_sm_rt not in", values, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_sm_rt between", value1, value2, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andDecQtySmRtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_sm_rt not between", value1, value2, "decQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtyIsNull() {
            addCriterion("cust_qty is null");
            return (Criteria) this;
        }

        public Criteria andCustQtyIsNotNull() {
            addCriterion("cust_qty is not null");
            return (Criteria) this;
        }

        public Criteria andCustQtyEqualTo(Integer value) {
            addCriterion("cust_qty =", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyNotEqualTo(Integer value) {
            addCriterion("cust_qty <>", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyGreaterThan(Integer value) {
            addCriterion("cust_qty >", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("cust_qty >=", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyLessThan(Integer value) {
            addCriterion("cust_qty <", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyLessThanOrEqualTo(Integer value) {
            addCriterion("cust_qty <=", value, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyIn(List<Integer> values) {
            addCriterion("cust_qty in", values, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyNotIn(List<Integer> values) {
            addCriterion("cust_qty not in", values, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyBetween(Integer value1, Integer value2) {
            addCriterion("cust_qty between", value1, value2, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("cust_qty not between", value1, value2, "custQty");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtIsNull() {
            addCriterion("cust_qty_sm_rt is null");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtIsNotNull() {
            addCriterion("cust_qty_sm_rt is not null");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtEqualTo(BigDecimal value) {
            addCriterion("cust_qty_sm_rt =", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtNotEqualTo(BigDecimal value) {
            addCriterion("cust_qty_sm_rt <>", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtGreaterThan(BigDecimal value) {
            addCriterion("cust_qty_sm_rt >", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cust_qty_sm_rt >=", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtLessThan(BigDecimal value) {
            addCriterion("cust_qty_sm_rt <", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cust_qty_sm_rt <=", value, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtIn(List<BigDecimal> values) {
            addCriterion("cust_qty_sm_rt in", values, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtNotIn(List<BigDecimal> values) {
            addCriterion("cust_qty_sm_rt not in", values, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cust_qty_sm_rt between", value1, value2, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andCustQtySmRtNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cust_qty_sm_rt not between", value1, value2, "custQtySmRt");
            return (Criteria) this;
        }

        public Criteria andHandleQtyIsNull() {
            addCriterion("handle_qty is null");
            return (Criteria) this;
        }

        public Criteria andHandleQtyIsNotNull() {
            addCriterion("handle_qty is not null");
            return (Criteria) this;
        }

        public Criteria andHandleQtyEqualTo(Integer value) {
            addCriterion("handle_qty =", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyNotEqualTo(Integer value) {
            addCriterion("handle_qty <>", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyGreaterThan(Integer value) {
            addCriterion("handle_qty >", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("handle_qty >=", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyLessThan(Integer value) {
            addCriterion("handle_qty <", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyLessThanOrEqualTo(Integer value) {
            addCriterion("handle_qty <=", value, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyIn(List<Integer> values) {
            addCriterion("handle_qty in", values, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyNotIn(List<Integer> values) {
            addCriterion("handle_qty not in", values, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyBetween(Integer value1, Integer value2) {
            addCriterion("handle_qty between", value1, value2, "handleQty");
            return (Criteria) this;
        }

        public Criteria andHandleQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("handle_qty not between", value1, value2, "handleQty");
            return (Criteria) this;
        }

        public Criteria andErrRateIsNull() {
            addCriterion("err_rate is null");
            return (Criteria) this;
        }

        public Criteria andErrRateIsNotNull() {
            addCriterion("err_rate is not null");
            return (Criteria) this;
        }

        public Criteria andErrRateEqualTo(BigDecimal value) {
            addCriterion("err_rate =", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateNotEqualTo(BigDecimal value) {
            addCriterion("err_rate <>", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateGreaterThan(BigDecimal value) {
            addCriterion("err_rate >", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("err_rate >=", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateLessThan(BigDecimal value) {
            addCriterion("err_rate <", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("err_rate <=", value, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateIn(List<BigDecimal> values) {
            addCriterion("err_rate in", values, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateNotIn(List<BigDecimal> values) {
            addCriterion("err_rate not in", values, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("err_rate between", value1, value2, "errRate");
            return (Criteria) this;
        }

        public Criteria andErrRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("err_rate not between", value1, value2, "errRate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_dec_stat_yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}