package org.saas.report.entity;

import java.math.BigDecimal;

public class S02DecAmt extends S02DecAmtKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_amt.dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal decAmt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_amt.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer custQty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_amt.dec_amt
     *
     * @return the value of s02_dec_amt.dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getDecAmt() {
        return decAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_amt.dec_amt
     *
     * @param decAmt the value for s02_dec_amt.dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecAmt(BigDecimal decAmt) {
        this.decAmt = decAmt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_amt.cust_qty
     *
     * @return the value of s02_dec_amt.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getCustQty() {
        return custQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_amt.cust_qty
     *
     * @param custQty the value for s02_dec_amt.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setCustQty(Integer custQty) {
        this.custQty = custQty;
    }
}