package org.saas.report.entity;

import java.math.BigDecimal;

public class S02DecStatYr {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String yr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal amt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.amt_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal amtSmRt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer decQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.dec_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal decQtySmRt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer custQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.cust_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal custQtySmRt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.handle_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer handleQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_dec_stat_yr.err_rate
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal errRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.yr
     *
     * @return the value of s02_dec_stat_yr.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getYr() {
        return yr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.yr
     *
     * @param yr the value for s02_dec_stat_yr.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setYr(String yr) {
        this.yr = yr == null ? null : yr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.amt
     *
     * @return the value of s02_dec_stat_yr.amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getAmt() {
        return amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.amt
     *
     * @param amt the value for s02_dec_stat_yr.amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setAmt(BigDecimal amt) {
        this.amt = amt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.amt_sm_rt
     *
     * @return the value of s02_dec_stat_yr.amt_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getAmtSmRt() {
        return amtSmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.amt_sm_rt
     *
     * @param amtSmRt the value for s02_dec_stat_yr.amt_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setAmtSmRt(BigDecimal amtSmRt) {
        this.amtSmRt = amtSmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.dec_qty
     *
     * @return the value of s02_dec_stat_yr.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getDecQty() {
        return decQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.dec_qty
     *
     * @param decQty the value for s02_dec_stat_yr.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQty(Integer decQty) {
        this.decQty = decQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.dec_qty_sm_rt
     *
     * @return the value of s02_dec_stat_yr.dec_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getDecQtySmRt() {
        return decQtySmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.dec_qty_sm_rt
     *
     * @param decQtySmRt the value for s02_dec_stat_yr.dec_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQtySmRt(BigDecimal decQtySmRt) {
        this.decQtySmRt = decQtySmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.cust_qty
     *
     * @return the value of s02_dec_stat_yr.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getCustQty() {
        return custQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.cust_qty
     *
     * @param custQty the value for s02_dec_stat_yr.cust_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setCustQty(Integer custQty) {
        this.custQty = custQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.cust_qty_sm_rt
     *
     * @return the value of s02_dec_stat_yr.cust_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getCustQtySmRt() {
        return custQtySmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.cust_qty_sm_rt
     *
     * @param custQtySmRt the value for s02_dec_stat_yr.cust_qty_sm_rt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setCustQtySmRt(BigDecimal custQtySmRt) {
        this.custQtySmRt = custQtySmRt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.handle_qty
     *
     * @return the value of s02_dec_stat_yr.handle_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getHandleQty() {
        return handleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.handle_qty
     *
     * @param handleQty the value for s02_dec_stat_yr.handle_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setHandleQty(Integer handleQty) {
        this.handleQty = handleQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_dec_stat_yr.err_rate
     *
     * @return the value of s02_dec_stat_yr.err_rate
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getErrRate() {
        return errRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_dec_stat_yr.err_rate
     *
     * @param errRate the value for s02_dec_stat_yr.err_rate
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setErrRate(BigDecimal errRate) {
        this.errRate = errRate;
    }
}