package org.saas.report.entity;

import java.util.ArrayList;
import java.util.List;

public class S02EntpCustDecQtyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public S02EntpCustDecQtyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYrIsNull() {
            addCriterion("yr is null");
            return (Criteria) this;
        }

        public Criteria andYrIsNotNull() {
            addCriterion("yr is not null");
            return (Criteria) this;
        }

        public Criteria andYrEqualTo(String value) {
            addCriterion("yr =", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotEqualTo(String value) {
            addCriterion("yr <>", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThan(String value) {
            addCriterion("yr >", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThanOrEqualTo(String value) {
            addCriterion("yr >=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThan(String value) {
            addCriterion("yr <", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThanOrEqualTo(String value) {
            addCriterion("yr <=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLike(String value) {
            addCriterion("yr like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotLike(String value) {
            addCriterion("yr not like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrIn(List<String> values) {
            addCriterion("yr in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotIn(List<String> values) {
            addCriterion("yr not in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrBetween(String value1, String value2) {
            addCriterion("yr between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotBetween(String value1, String value2) {
            addCriterion("yr not between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andDtTypIsNull() {
            addCriterion("dt_typ is null");
            return (Criteria) this;
        }

        public Criteria andDtTypIsNotNull() {
            addCriterion("dt_typ is not null");
            return (Criteria) this;
        }

        public Criteria andDtTypEqualTo(String value) {
            addCriterion("dt_typ =", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotEqualTo(String value) {
            addCriterion("dt_typ <>", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypGreaterThan(String value) {
            addCriterion("dt_typ >", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypGreaterThanOrEqualTo(String value) {
            addCriterion("dt_typ >=", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLessThan(String value) {
            addCriterion("dt_typ <", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLessThanOrEqualTo(String value) {
            addCriterion("dt_typ <=", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLike(String value) {
            addCriterion("dt_typ like", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotLike(String value) {
            addCriterion("dt_typ not like", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypIn(List<String> values) {
            addCriterion("dt_typ in", values, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotIn(List<String> values) {
            addCriterion("dt_typ not in", values, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypBetween(String value1, String value2) {
            addCriterion("dt_typ between", value1, value2, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotBetween(String value1, String value2) {
            addCriterion("dt_typ not between", value1, value2, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDecDtIsNull() {
            addCriterion("dec_dt is null");
            return (Criteria) this;
        }

        public Criteria andDecDtIsNotNull() {
            addCriterion("dec_dt is not null");
            return (Criteria) this;
        }

        public Criteria andDecDtEqualTo(String value) {
            addCriterion("dec_dt =", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotEqualTo(String value) {
            addCriterion("dec_dt <>", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtGreaterThan(String value) {
            addCriterion("dec_dt >", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtGreaterThanOrEqualTo(String value) {
            addCriterion("dec_dt >=", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLessThan(String value) {
            addCriterion("dec_dt <", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLessThanOrEqualTo(String value) {
            addCriterion("dec_dt <=", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLike(String value) {
            addCriterion("dec_dt like", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotLike(String value) {
            addCriterion("dec_dt not like", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtIn(List<String> values) {
            addCriterion("dec_dt in", values, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotIn(List<String> values) {
            addCriterion("dec_dt not in", values, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtBetween(String value1, String value2) {
            addCriterion("dec_dt between", value1, value2, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotBetween(String value1, String value2) {
            addCriterion("dec_dt not between", value1, value2, "decDt");
            return (Criteria) this;
        }

        public Criteria andEntpNmIsNull() {
            addCriterion("entp_nm is null");
            return (Criteria) this;
        }

        public Criteria andEntpNmIsNotNull() {
            addCriterion("entp_nm is not null");
            return (Criteria) this;
        }

        public Criteria andEntpNmEqualTo(String value) {
            addCriterion("entp_nm =", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmNotEqualTo(String value) {
            addCriterion("entp_nm <>", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmGreaterThan(String value) {
            addCriterion("entp_nm >", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmGreaterThanOrEqualTo(String value) {
            addCriterion("entp_nm >=", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmLessThan(String value) {
            addCriterion("entp_nm <", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmLessThanOrEqualTo(String value) {
            addCriterion("entp_nm <=", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmLike(String value) {
            addCriterion("entp_nm like", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmNotLike(String value) {
            addCriterion("entp_nm not like", value, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmIn(List<String> values) {
            addCriterion("entp_nm in", values, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmNotIn(List<String> values) {
            addCriterion("entp_nm not in", values, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmBetween(String value1, String value2) {
            addCriterion("entp_nm between", value1, value2, "entpNm");
            return (Criteria) this;
        }

        public Criteria andEntpNmNotBetween(String value1, String value2) {
            addCriterion("entp_nm not between", value1, value2, "entpNm");
            return (Criteria) this;
        }

        public Criteria andCustNmIsNull() {
            addCriterion("cust_nm is null");
            return (Criteria) this;
        }

        public Criteria andCustNmIsNotNull() {
            addCriterion("cust_nm is not null");
            return (Criteria) this;
        }

        public Criteria andCustNmEqualTo(String value) {
            addCriterion("cust_nm =", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotEqualTo(String value) {
            addCriterion("cust_nm <>", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmGreaterThan(String value) {
            addCriterion("cust_nm >", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmGreaterThanOrEqualTo(String value) {
            addCriterion("cust_nm >=", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLessThan(String value) {
            addCriterion("cust_nm <", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLessThanOrEqualTo(String value) {
            addCriterion("cust_nm <=", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmLike(String value) {
            addCriterion("cust_nm like", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotLike(String value) {
            addCriterion("cust_nm not like", value, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmIn(List<String> values) {
            addCriterion("cust_nm in", values, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotIn(List<String> values) {
            addCriterion("cust_nm not in", values, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmBetween(String value1, String value2) {
            addCriterion("cust_nm between", value1, value2, "custNm");
            return (Criteria) this;
        }

        public Criteria andCustNmNotBetween(String value1, String value2) {
            addCriterion("cust_nm not between", value1, value2, "custNm");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescIsNull() {
            addCriterion("entp_typ_desc is null");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescIsNotNull() {
            addCriterion("entp_typ_desc is not null");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescEqualTo(String value) {
            addCriterion("entp_typ_desc =", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescNotEqualTo(String value) {
            addCriterion("entp_typ_desc <>", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescGreaterThan(String value) {
            addCriterion("entp_typ_desc >", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescGreaterThanOrEqualTo(String value) {
            addCriterion("entp_typ_desc >=", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescLessThan(String value) {
            addCriterion("entp_typ_desc <", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescLessThanOrEqualTo(String value) {
            addCriterion("entp_typ_desc <=", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescLike(String value) {
            addCriterion("entp_typ_desc like", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescNotLike(String value) {
            addCriterion("entp_typ_desc not like", value, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescIn(List<String> values) {
            addCriterion("entp_typ_desc in", values, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescNotIn(List<String> values) {
            addCriterion("entp_typ_desc not in", values, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescBetween(String value1, String value2) {
            addCriterion("entp_typ_desc between", value1, value2, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andEntpTypDescNotBetween(String value1, String value2) {
            addCriterion("entp_typ_desc not between", value1, value2, "entpTypDesc");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIsNull() {
            addCriterion("im_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIsNotNull() {
            addCriterion("im_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andImDecQtyEqualTo(Integer value) {
            addCriterion("im_dec_qty =", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotEqualTo(Integer value) {
            addCriterion("im_dec_qty <>", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyGreaterThan(Integer value) {
            addCriterion("im_dec_qty >", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("im_dec_qty >=", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyLessThan(Integer value) {
            addCriterion("im_dec_qty <", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("im_dec_qty <=", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIn(List<Integer> values) {
            addCriterion("im_dec_qty in", values, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotIn(List<Integer> values) {
            addCriterion("im_dec_qty not in", values, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("im_dec_qty between", value1, value2, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("im_dec_qty not between", value1, value2, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIsNull() {
            addCriterion("e_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIsNotNull() {
            addCriterion("e_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andEDecQtyEqualTo(Integer value) {
            addCriterion("e_dec_qty =", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotEqualTo(Integer value) {
            addCriterion("e_dec_qty <>", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyGreaterThan(Integer value) {
            addCriterion("e_dec_qty >", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_dec_qty >=", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyLessThan(Integer value) {
            addCriterion("e_dec_qty <", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("e_dec_qty <=", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIn(List<Integer> values) {
            addCriterion("e_dec_qty in", values, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotIn(List<Integer> values) {
            addCriterion("e_dec_qty not in", values, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("e_dec_qty between", value1, value2, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("e_dec_qty not between", value1, value2, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIsNull() {
            addCriterion("tot_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIsNotNull() {
            addCriterion("tot_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyEqualTo(Integer value) {
            addCriterion("tot_dec_qty =", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotEqualTo(Integer value) {
            addCriterion("tot_dec_qty <>", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyGreaterThan(Integer value) {
            addCriterion("tot_dec_qty >", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("tot_dec_qty >=", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyLessThan(Integer value) {
            addCriterion("tot_dec_qty <", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("tot_dec_qty <=", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIn(List<Integer> values) {
            addCriterion("tot_dec_qty in", values, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotIn(List<Integer> values) {
            addCriterion("tot_dec_qty not in", values, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("tot_dec_qty between", value1, value2, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("tot_dec_qty not between", value1, value2, "totDecQty");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_entp_cust_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}