package org.saas.report.entity;

public class S02EntpDecQtyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String yr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String dtTyp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String decDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.entp_typ_desc
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String entpTypDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.entp_nm
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private String entpNm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.yr
     *
     * @return the value of s02_entp_dec_qty.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getYr() {
        return yr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.yr
     *
     * @param yr the value for s02_entp_dec_qty.yr
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setYr(String yr) {
        this.yr = yr == null ? null : yr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.dt_typ
     *
     * @return the value of s02_entp_dec_qty.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getDtTyp() {
        return dtTyp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.dt_typ
     *
     * @param dtTyp the value for s02_entp_dec_qty.dt_typ
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDtTyp(String dtTyp) {
        this.dtTyp = dtTyp == null ? null : dtTyp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.dec_dt
     *
     * @return the value of s02_entp_dec_qty.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getDecDt() {
        return decDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.dec_dt
     *
     * @param decDt the value for s02_entp_dec_qty.dec_dt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecDt(String decDt) {
        this.decDt = decDt == null ? null : decDt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.entp_typ_desc
     *
     * @return the value of s02_entp_dec_qty.entp_typ_desc
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getEntpTypDesc() {
        return entpTypDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.entp_typ_desc
     *
     * @param entpTypDesc the value for s02_entp_dec_qty.entp_typ_desc
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setEntpTypDesc(String entpTypDesc) {
        this.entpTypDesc = entpTypDesc == null ? null : entpTypDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.entp_nm
     *
     * @return the value of s02_entp_dec_qty.entp_nm
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getEntpNm() {
        return entpNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.entp_nm
     *
     * @param entpNm the value for s02_entp_dec_qty.entp_nm
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setEntpNm(String entpNm) {
        this.entpNm = entpNm == null ? null : entpNm.trim();
    }
}