package org.saas.report.entity;

public class S02EntpDecQty extends S02EntpDecQtyKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_entp_dec_qty.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer decQty;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_entp_dec_qty.dec_qty
     *
     * @return the value of s02_entp_dec_qty.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getDecQty() {
        return decQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_entp_dec_qty.dec_qty
     *
     * @param decQty the value for s02_entp_dec_qty.dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQty(Integer decQty) {
        this.decQty = decQty;
    }
}