package org.saas.report.entity;

import java.math.BigDecimal;

public class S02IeDecStat extends S02IeDecStatKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.im_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer imDecQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.e_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer eDecQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.tot_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private Integer totDecQty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.dec_qty_strans_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal decQtyStransPct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.dec_qty_air_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal decQtyAirPct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column s02_ie_dec_stat.dec_qty_oth_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    private BigDecimal decQtyOthPct;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.im_dec_qty
     *
     * @return the value of s02_ie_dec_stat.im_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getImDecQty() {
        return imDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.im_dec_qty
     *
     * @param imDecQty the value for s02_ie_dec_stat.im_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setImDecQty(Integer imDecQty) {
        this.imDecQty = imDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.e_dec_qty
     *
     * @return the value of s02_ie_dec_stat.e_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer geteDecQty() {
        return eDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.e_dec_qty
     *
     * @param eDecQty the value for s02_ie_dec_stat.e_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void seteDecQty(Integer eDecQty) {
        this.eDecQty = eDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.tot_dec_qty
     *
     * @return the value of s02_ie_dec_stat.tot_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Integer getTotDecQty() {
        return totDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.tot_dec_qty
     *
     * @param totDecQty the value for s02_ie_dec_stat.tot_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setTotDecQty(Integer totDecQty) {
        this.totDecQty = totDecQty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.dec_qty_strans_pct
     *
     * @return the value of s02_ie_dec_stat.dec_qty_strans_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getDecQtyStransPct() {
        return decQtyStransPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.dec_qty_strans_pct
     *
     * @param decQtyStransPct the value for s02_ie_dec_stat.dec_qty_strans_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQtyStransPct(BigDecimal decQtyStransPct) {
        this.decQtyStransPct = decQtyStransPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.dec_qty_air_pct
     *
     * @return the value of s02_ie_dec_stat.dec_qty_air_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getDecQtyAirPct() {
        return decQtyAirPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.dec_qty_air_pct
     *
     * @param decQtyAirPct the value for s02_ie_dec_stat.dec_qty_air_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQtyAirPct(BigDecimal decQtyAirPct) {
        this.decQtyAirPct = decQtyAirPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column s02_ie_dec_stat.dec_qty_oth_pct
     *
     * @return the value of s02_ie_dec_stat.dec_qty_oth_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public BigDecimal getDecQtyOthPct() {
        return decQtyOthPct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column s02_ie_dec_stat.dec_qty_oth_pct
     *
     * @param decQtyOthPct the value for s02_ie_dec_stat.dec_qty_oth_pct
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDecQtyOthPct(BigDecimal decQtyOthPct) {
        this.decQtyOthPct = decQtyOthPct;
    }
}