package org.saas.report.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class S02IeDecStatExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public S02IeDecStatExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andYrIsNull() {
            addCriterion("yr is null");
            return (Criteria) this;
        }

        public Criteria andYrIsNotNull() {
            addCriterion("yr is not null");
            return (Criteria) this;
        }

        public Criteria andYrEqualTo(String value) {
            addCriterion("yr =", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotEqualTo(String value) {
            addCriterion("yr <>", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThan(String value) {
            addCriterion("yr >", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrGreaterThanOrEqualTo(String value) {
            addCriterion("yr >=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThan(String value) {
            addCriterion("yr <", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLessThanOrEqualTo(String value) {
            addCriterion("yr <=", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrLike(String value) {
            addCriterion("yr like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotLike(String value) {
            addCriterion("yr not like", value, "yr");
            return (Criteria) this;
        }

        public Criteria andYrIn(List<String> values) {
            addCriterion("yr in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotIn(List<String> values) {
            addCriterion("yr not in", values, "yr");
            return (Criteria) this;
        }

        public Criteria andYrBetween(String value1, String value2) {
            addCriterion("yr between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andYrNotBetween(String value1, String value2) {
            addCriterion("yr not between", value1, value2, "yr");
            return (Criteria) this;
        }

        public Criteria andDtTypIsNull() {
            addCriterion("dt_typ is null");
            return (Criteria) this;
        }

        public Criteria andDtTypIsNotNull() {
            addCriterion("dt_typ is not null");
            return (Criteria) this;
        }

        public Criteria andDtTypEqualTo(String value) {
            addCriterion("dt_typ =", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotEqualTo(String value) {
            addCriterion("dt_typ <>", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypGreaterThan(String value) {
            addCriterion("dt_typ >", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypGreaterThanOrEqualTo(String value) {
            addCriterion("dt_typ >=", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLessThan(String value) {
            addCriterion("dt_typ <", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLessThanOrEqualTo(String value) {
            addCriterion("dt_typ <=", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypLike(String value) {
            addCriterion("dt_typ like", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotLike(String value) {
            addCriterion("dt_typ not like", value, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypIn(List<String> values) {
            addCriterion("dt_typ in", values, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotIn(List<String> values) {
            addCriterion("dt_typ not in", values, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypBetween(String value1, String value2) {
            addCriterion("dt_typ between", value1, value2, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDtTypNotBetween(String value1, String value2) {
            addCriterion("dt_typ not between", value1, value2, "dtTyp");
            return (Criteria) this;
        }

        public Criteria andDecDtIsNull() {
            addCriterion("dec_dt is null");
            return (Criteria) this;
        }

        public Criteria andDecDtIsNotNull() {
            addCriterion("dec_dt is not null");
            return (Criteria) this;
        }

        public Criteria andDecDtEqualTo(String value) {
            addCriterion("dec_dt =", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotEqualTo(String value) {
            addCriterion("dec_dt <>", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtGreaterThan(String value) {
            addCriterion("dec_dt >", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtGreaterThanOrEqualTo(String value) {
            addCriterion("dec_dt >=", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLessThan(String value) {
            addCriterion("dec_dt <", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLessThanOrEqualTo(String value) {
            addCriterion("dec_dt <=", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtLike(String value) {
            addCriterion("dec_dt like", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotLike(String value) {
            addCriterion("dec_dt not like", value, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtIn(List<String> values) {
            addCriterion("dec_dt in", values, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotIn(List<String> values) {
            addCriterion("dec_dt not in", values, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtBetween(String value1, String value2) {
            addCriterion("dec_dt between", value1, value2, "decDt");
            return (Criteria) this;
        }

        public Criteria andDecDtNotBetween(String value1, String value2) {
            addCriterion("dec_dt not between", value1, value2, "decDt");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIsNull() {
            addCriterion("im_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIsNotNull() {
            addCriterion("im_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andImDecQtyEqualTo(Integer value) {
            addCriterion("im_dec_qty =", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotEqualTo(Integer value) {
            addCriterion("im_dec_qty <>", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyGreaterThan(Integer value) {
            addCriterion("im_dec_qty >", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("im_dec_qty >=", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyLessThan(Integer value) {
            addCriterion("im_dec_qty <", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("im_dec_qty <=", value, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyIn(List<Integer> values) {
            addCriterion("im_dec_qty in", values, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotIn(List<Integer> values) {
            addCriterion("im_dec_qty not in", values, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("im_dec_qty between", value1, value2, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andImDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("im_dec_qty not between", value1, value2, "imDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIsNull() {
            addCriterion("e_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIsNotNull() {
            addCriterion("e_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andEDecQtyEqualTo(Integer value) {
            addCriterion("e_dec_qty =", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotEqualTo(Integer value) {
            addCriterion("e_dec_qty <>", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyGreaterThan(Integer value) {
            addCriterion("e_dec_qty >", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("e_dec_qty >=", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyLessThan(Integer value) {
            addCriterion("e_dec_qty <", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("e_dec_qty <=", value, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyIn(List<Integer> values) {
            addCriterion("e_dec_qty in", values, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotIn(List<Integer> values) {
            addCriterion("e_dec_qty not in", values, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("e_dec_qty between", value1, value2, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andEDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("e_dec_qty not between", value1, value2, "eDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIsNull() {
            addCriterion("tot_dec_qty is null");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIsNotNull() {
            addCriterion("tot_dec_qty is not null");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyEqualTo(Integer value) {
            addCriterion("tot_dec_qty =", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotEqualTo(Integer value) {
            addCriterion("tot_dec_qty <>", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyGreaterThan(Integer value) {
            addCriterion("tot_dec_qty >", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyGreaterThanOrEqualTo(Integer value) {
            addCriterion("tot_dec_qty >=", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyLessThan(Integer value) {
            addCriterion("tot_dec_qty <", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyLessThanOrEqualTo(Integer value) {
            addCriterion("tot_dec_qty <=", value, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyIn(List<Integer> values) {
            addCriterion("tot_dec_qty in", values, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotIn(List<Integer> values) {
            addCriterion("tot_dec_qty not in", values, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyBetween(Integer value1, Integer value2) {
            addCriterion("tot_dec_qty between", value1, value2, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andTotDecQtyNotBetween(Integer value1, Integer value2) {
            addCriterion("tot_dec_qty not between", value1, value2, "totDecQty");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctIsNull() {
            addCriterion("dec_qty_strans_pct is null");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctIsNotNull() {
            addCriterion("dec_qty_strans_pct is not null");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctEqualTo(BigDecimal value) {
            addCriterion("dec_qty_strans_pct =", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctNotEqualTo(BigDecimal value) {
            addCriterion("dec_qty_strans_pct <>", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctGreaterThan(BigDecimal value) {
            addCriterion("dec_qty_strans_pct >", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_strans_pct >=", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctLessThan(BigDecimal value) {
            addCriterion("dec_qty_strans_pct <", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_strans_pct <=", value, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctIn(List<BigDecimal> values) {
            addCriterion("dec_qty_strans_pct in", values, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctNotIn(List<BigDecimal> values) {
            addCriterion("dec_qty_strans_pct not in", values, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_strans_pct between", value1, value2, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyStransPctNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_strans_pct not between", value1, value2, "decQtyStransPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctIsNull() {
            addCriterion("dec_qty_air_pct is null");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctIsNotNull() {
            addCriterion("dec_qty_air_pct is not null");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctEqualTo(BigDecimal value) {
            addCriterion("dec_qty_air_pct =", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctNotEqualTo(BigDecimal value) {
            addCriterion("dec_qty_air_pct <>", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctGreaterThan(BigDecimal value) {
            addCriterion("dec_qty_air_pct >", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_air_pct >=", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctLessThan(BigDecimal value) {
            addCriterion("dec_qty_air_pct <", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_air_pct <=", value, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctIn(List<BigDecimal> values) {
            addCriterion("dec_qty_air_pct in", values, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctNotIn(List<BigDecimal> values) {
            addCriterion("dec_qty_air_pct not in", values, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_air_pct between", value1, value2, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyAirPctNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_air_pct not between", value1, value2, "decQtyAirPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctIsNull() {
            addCriterion("dec_qty_oth_pct is null");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctIsNotNull() {
            addCriterion("dec_qty_oth_pct is not null");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctEqualTo(BigDecimal value) {
            addCriterion("dec_qty_oth_pct =", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctNotEqualTo(BigDecimal value) {
            addCriterion("dec_qty_oth_pct <>", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctGreaterThan(BigDecimal value) {
            addCriterion("dec_qty_oth_pct >", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_oth_pct >=", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctLessThan(BigDecimal value) {
            addCriterion("dec_qty_oth_pct <", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dec_qty_oth_pct <=", value, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctIn(List<BigDecimal> values) {
            addCriterion("dec_qty_oth_pct in", values, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctNotIn(List<BigDecimal> values) {
            addCriterion("dec_qty_oth_pct not in", values, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_oth_pct between", value1, value2, "decQtyOthPct");
            return (Criteria) this;
        }

        public Criteria andDecQtyOthPctNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dec_qty_oth_pct not between", value1, value2, "decQtyOthPct");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated do_not_delete_during_merge Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}