package org.saas.report.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.saas.report.entity.S02DecAmt;
import org.saas.report.entity.S02DecAmtExample;
import org.saas.report.entity.S02DecAmtKey;

public interface S02DecAmtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    long countByExample(S02DecAmtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByExample(S02DecAmtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByPrimaryKey(S02DecAmtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insert(S02DecAmt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insertSelective(S02DecAmt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    List<S02DecAmt> selectByExample(S02DecAmtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    S02DecAmt selectByPrimaryKey(S02DecAmtKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExampleSelective(@Param("row") S02DecAmt row, @Param("example") S02DecAmtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExample(@Param("row") S02DecAmt row, @Param("example") S02DecAmtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKeySelective(S02DecAmt row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_dec_amt
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKey(S02DecAmt row);
}