package org.saas.report.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.saas.report.entity.S02EntpDecQty;
import org.saas.report.entity.S02EntpDecQtyExample;
import org.saas.report.entity.S02EntpDecQtyKey;

public interface S02EntpDecQtyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    long countByExample(S02EntpDecQtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByExample(S02EntpDecQtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByPrimaryKey(S02EntpDecQtyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insert(S02EntpDecQty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insertSelective(S02EntpDecQty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    List<S02EntpDecQty> selectByExample(S02EntpDecQtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    S02EntpDecQty selectByPrimaryKey(S02EntpDecQtyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExampleSelective(@Param("row") S02EntpDecQty row, @Param("example") S02EntpDecQtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExample(@Param("row") S02EntpDecQty row, @Param("example") S02EntpDecQtyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKeySelective(S02EntpDecQty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_entp_dec_qty
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKey(S02EntpDecQty row);
}