package org.saas.report.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.saas.report.entity.S02IeDecStat;
import org.saas.report.entity.S02IeDecStatExample;
import org.saas.report.entity.S02IeDecStatKey;

public interface S02IeDecStatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    long countByExample(S02IeDecStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByExample(S02IeDecStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int deleteByPrimaryKey(S02IeDecStatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insert(S02IeDecStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int insertSelective(S02IeDecStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    List<S02IeDecStat> selectByExample(S02IeDecStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    S02IeDecStat selectByPrimaryKey(S02IeDecStatKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExampleSelective(@Param("row") S02IeDecStat row, @Param("example") S02IeDecStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByExample(@Param("row") S02IeDecStat row, @Param("example") S02IeDecStatExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKeySelective(S02IeDecStat row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table s02_ie_dec_stat
     *
     * @mbg.generated Thu Jun 23 14:31:43 CST 2022
     */
    int updateByPrimaryKey(S02IeDecStat row);
}